name: DanDonahoe
description: web development and stuff
meta_description: "Dan Donahoe Developer Blog"

markdown: kramdown
highlighter: pygments
logo: false
paginate: 15
baseurl: /
domain_name: 'http://dandonahoe.com'
google_analytics: 'UA-47127035-8'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'http://dandonahoe.com'
author:         'Dan Donahoe'
